config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magenta-insect.sh
        container: qc.acc_chewy-carmine-giraffe
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-pumpkin-meerkat.sh
        container: qc.doc_sleazy-emerald-russel
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-saffron-squirt.sh
        container: qc.doc_whiny-aquamarine-greyhound
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chocolate-capuchin.sh
        container: qc.doc_woozy-myrtle-crane
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-emerald-buffalo.sh
        container: qc.lic_leaky-carmine-capybara
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-khaki-dachshund.sh
        container: qc.met_cozy-olive-chicken
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-azure-spoonbill.sh
        container: qc.sec_tacky-sepia-burmese
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sangria-hippopotamus.sh
        container: qc.sty_craggy-ivory-squirrel
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-auburn-devil.sh
        container: qc.ver_surly-orchid-zonkey
timeout: 5400
