config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-eggplant-havanese.sh
        container: qc.acc_skimpy-mauve-zebu
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-puce-insect.sh
        container: qc.doc_homely-teal-slug
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-lemon-seahorse.sh
        container: qc.doc_fuzzy-olivine-zonkey
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-olive-shark.sh
        container: qc.doc_bluesy-rust-albatross
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-fuchsia-wolf.sh
        container: qc.lic_pretty-tomato-gharial
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-tomato-moose.sh
        container: qc.met_flaky-red-squid
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-bronze-zorse.sh
        container: qc.sec_crappy-indigo-robin
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-asparagus-gorilla.sh
        container: qc.sty_hasty-flax-sheep
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-viridian-camel.sh
        container: qc.ver_sleepy-sapphire-worm
timeout: 5400
