config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cerulean-walrus.sh
        container: qc.acc_boozy-lilac-squirrel
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-silver-impala.sh
        container: qc.doc_lousy-harlequin-bobcat
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-beige-donkey.sh
        container: qc.doc_smelly-flax-termite
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ochre-seahorse.sh
        container: qc.doc_pokey-maroon-crocodile
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cyan-newt.sh
        container: qc.lic_stuffy-bistre-wombat
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-plum-civet.sh
        container: qc.met_silly-persimmon-cuscus
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-silver-toad.sh
        container: qc.sec_snoopy-indigo-hippopotamus
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-xanthic-opossum.sh
        container: qc.sty_scummy-olive-serval
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-salmon-mayfly.sh
        container: qc.ver_shabby-lemon-liger
timeout: 5400
