config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-bronze-collie.sh
        container: qc.acc_shabby-beige-seal
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cobalt-bracke.sh
        container: qc.doc_surly-alizarin-olm
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-lavender-loon.sh
        container: qc.doc_pretty-harlequin-tiger
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-brass-impala.sh
        container: qc.doc_ready-tangerine-mole
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amber-cheetah.sh
        container: qc.lic_sleazy-eggplant-mastiff
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cardinal-uguisu.sh
        container: qc.met_gloppy-viridian-kakapo
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cobalt-axolotl.sh
        container: qc.sec_grumpy-silver-mole
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-magnolia-elephant.sh
        container: qc.sty_whiny-gamboge-dugong
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-bistre-wallaby.sh
        container: qc.ver_hasty-peach-rat
timeout: 5400
