config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-auburn-hummingbird.sh
        container: qc.acc_slimy-black-dhole
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-amaranth-impala.sh
        container: qc.doc_flaky-green-dragon
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cornflower-dormouse.sh
        container: qc.doc_hilly-gamboge-angelfish
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-jade-tamarin.sh
        container: qc.doc_flabby-burgundy-chimpanzee
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-smalt-loon.sh
        container: qc.lic_stealthy-persimmon-hamster
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-mustard-crane.sh
        container: qc.met_gimpy-cinnamon-salamander
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-persimmon-macaw.sh
        container: qc.sec_lanky-saffron-woodpecker
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-wisteria-russel.sh
        container: qc.sty_lumpy-auburn-gibbon
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-dandelion-alligator.sh
        container: qc.ver_queasy-smalt-moorhen
timeout: 5400
