config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-fuchsia-sheepdog.sh
        container: qc.acc_crabby-razzmatazz-baboon
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-emerald-fousek.sh
        container: qc.doc_sleepy-puce-argentino
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chocolate-dunker.sh
        container: qc.doc_squeaky-bistre-liger
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-zucchini-donkey.sh
        container: qc.doc_sunny-thistle-angora
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-buff-impala.sh
        container: qc.lic_surly-aquamarine-crocodile
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-firebrick-squirt.sh
        container: qc.met_jumpy-ultramarine-jaguar
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-teal-rat.sh
        container: qc.sec_shaggy-heliotrope-fossa
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-heliotrope-paradise.sh
        container: qc.sty_slimy-smalt-discus
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cardinal-okapi.sh
        container: qc.ver_queasy-mauve-owl
timeout: 5400
