config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-yellow-macaw.sh
        container: qc.acc_paltry-crimson-cassowary
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-linen-dragon.sh
        container: qc.doc_gamy-harlequin-starfish
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-bronze-nightingale.sh
        container: qc.doc_pretty-turquoise-dodo
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-fuchsia-mist.sh
        container: qc.doc_shaky-periwinkle-jellyfish
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-amber-anteater.sh
        container: qc.lic_shabby-ivory-setter
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-celadon-manatee.sh
        container: qc.met_droopy-cerulean-shrimp
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-sepia-newfoundland.sh
        container: qc.sec_sleazy-taupe-chipmunk
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-olive-schnauzer.sh
        container: qc.sty_baggy-harlequin-dane
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-teal-buzzard.sh
        container: qc.ver_shabby-azure-raccoon
timeout: 5400
