config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-crimson-hyena.sh
        container: qc.acc_pretty-magnolia-eel
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-rust-caterpillar.sh
        container: qc.doc_sleazy-carmine-chihuahua
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cerise-flounder.sh
        container: qc.doc_homey-grey-dormouse
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-olivine-wildebeest.sh
        container: qc.doc_nippy-khaki-zorse
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-turquoise-squirrel.sh
        container: qc.lic_tacky-denim-giraffe
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-gold-cheetah.sh
        container: qc.met_chummy-dandelion-axolotl
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cinnabar-duck.sh
        container: qc.sec_zippy-zucchini-tetra
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ultramarine-crocodile.sh
        container: qc.sty_nerdy-viridian-indri
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-beige-emu.sh
        container: qc.ver_gloppy-chocolate-binturong
timeout: 5400
