config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-vermilion-falcon.sh
        container: qc.acc_skinny-copper-fish
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-lemon-buzzard.sh
        container: qc.doc_slimy-ivory-orangutan
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-buff-okapi.sh
        container: qc.doc_tasty-ochre-bombay
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-platinum-bird.sh
        container: qc.doc_hazy-mauve-slug
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cyan-iguana.sh
        container: qc.lic_frumpy-chestnut-cattle
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-asparagus-snail.sh
        container: qc.met_hilly-sapphire-capybara
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-orchid-dachsbracke.sh
        container: qc.sec_gimpy-khaki-spaniel
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cerulean-harrier.sh
        container: qc.sty_wimpy-blue-spider
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-asparagus-badger.sh
        container: qc.ver_cheeky-cerise-peccary
timeout: 5400
