config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cyan-barb.sh
        container: qc.acc_tacky-coral-tamarin
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-razzmatazz-tang.sh
        container: qc.doc_snazzy-magenta-bloodhound
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pink-slug.sh
        container: qc.doc_wheezy-carmine-wasp
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-denim-kingfisher.sh
        container: qc.doc_cheeky-bronze-weasel
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-tan-mongoose.sh
        container: qc.lic_goopy-beige-retriever
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-goldenrod-flounder.sh
        container: qc.met_lousy-rust-woodpecker
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ultramarine-mastiff.sh
        container: qc.sec_wiggy-black-tortoise
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-auburn-dog.sh
        container: qc.sty_sloppy-grey-squid
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-yellow-okapi.sh
        container: qc.ver_messy-cinnabar-snake
timeout: 5400
