config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-khaki-dane.sh
        container: qc.acc_bluesy-brown-mouse
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-goldenrod-worm.sh
        container: qc.doc_paltry-pumpkin-harrier
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cobalt-urchin.sh
        container: qc.doc_shaggy-lime-wrasse
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-orange-scorpion.sh
        container: qc.doc_randy-persimmon-labradoodle
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-dandelion-badger.sh
        container: qc.lic_flabby-rose-badger
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cinnamon-rat.sh
        container: qc.met_shabby-mustard-hornet
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-wheat-owl.sh
        container: qc.sec_messy-cerise-setter
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-crimson-dragonfly.sh
        container: qc.sty_sunny-razzmatazz-iguana
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-chestnut-cougar.sh
        container: qc.ver_greasy-carmine-emu
timeout: 5400
