config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/m3csdirest:
      branch: main
      repo: https://github.com/stevenjgibbons/m3csdirest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amethyst-hare.sh
        container: qc.acc_hilly-linen-mole
  QC.Doc:
    repos:
      github.com/stevenjgibbons/m3csdirest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-goldenrod-budgerigar.sh
        container: qc.doc_thirsty-ecru-termite
      github.com/stevenjgibbons/m3csdirest git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-orchid-tarantula.sh
        container: qc.doc_sickly-apricot-dodo
      github.com/stevenjgibbons/m3csdirest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-malachite-reindeer.sh
        container: qc.doc_flaky-bistre-schnauzer
  QC.Lic:
    repos:
      github.com/stevenjgibbons/m3csdirest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-bronze-tetra.sh
        container: qc.lic_shabby-khaki-cattle
  QC.Met:
    repos:
      github.com/stevenjgibbons/m3csdirest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-violet-bear.sh
        container: qc.met_messy-ultramarine-tarantula
  QC.Sec:
    repos:
      github.com/stevenjgibbons/m3csdirest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-dandelion-caracal.sh
        container: qc.sec_jumpy-bistre-swan
  QC.Sty:
    repos:
      github.com/stevenjgibbons/m3csdirest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chocolate-akita.sh
        container: qc.sty_hilly-amaranth-grouse
  QC.Ver:
    repos:
      github.com/stevenjgibbons/m3csdirest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-aqua-wrasse.sh
        container: qc.ver_wheezy-chestnut-rottweiler
timeout: 5400
